
name: Deploying webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE_GROUP: aguadamillas_students_1
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: kathe

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

      - name: Deploy Infrastructure
        run: |
          az deployment group create \
          --name ${{ env.USER_ALIAS }}Deployment \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --template-file ./main.bicep \
          --parameters @parameters/parameters.json \
          --parameters DOCKER_REGISTRY_SERVER_URL=${{ secrets.DOCKER_REGISTRY_SERVER_URL }} \
                        DOCKER_REGISTRY_SERVER_USERNAME=${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }} \
                        DOCKER_REGISTRY_SERVER_PASSWORD=${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}